apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mongodbs
  name: mongodbs
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongodbs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongodbs
    spec:
      containers:
      - image: mongo
        name: mongodbs
        ports:
        - containerPort: 27017
        resources: {}
status: {}
