apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: musicmatch
  name: musicmatch
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    run: musicmatch
  type: NodePort
status:
  loadBalancer: {}
